In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("DATA SET\Delivery_Logistics.csv")
df.head(5)

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,250.99,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000008,no,delivered,3,1632.7206
1,250.99,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000003,no,delivered,5,640.1700
2,250.99,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,1970-01-01 00:00:00.000000010,1970-01-01 00:00:00.000000016,no,delivered,4,1448.1700
3,250.99,dhl,electronics,ev van,same day,east,cold,269.7,12.69,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000008,no,delivered,3,1486.5700
4,250.99,dhl,clothing,van,two day,north,foggy,256.7,37.02,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000016,no,delivered,4,1394.5600

In [4]:
df.shape

(25000, 15)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   delivery_id          25000 non-null  float64
 1   delivery_partner     25000 non-null  object
 2   package_type         25000 non-null  object
 3   vehicle_type         25000 non-null  object
 4   delivery_mode        25000 non-null  object
 5   region               25000 non-null  object
 6   weather_condition    25000 non-null  object
 7   distance_km          25000 non-null  float64
 8   package_weight_kg    25000 non-null  float64
 9   delivery_time_hours  25000 non-null  object
 10  expected_time_hours  25000 non-null  object
 11  delayed              25000 non-null  object
 12  delivery_status      25000 non-null  object
 13  delivery_rating      25000 non-null  int64
 14  delivery_cost        25000 non-null  float64
dtypes: float64(4), int64(1), object(10)
memory usage: 2.9+ MB

In [5]:
df.describe()

,delivery_id,distance_km,package_weight_kg,delivery_rating,delivery_cost
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,12500.500000,150.390436,25.145898,3.666000,864.944579
std,7212.732314,86.409745,14.368663,1.149964,435.712593
min,250.990000,3.600000,0.670000,1.000000,95.667400
25%,6250.750000,75.900000,12.680000,3.000000,490.800000
50%,12500.500000,151.000000,25.145000,4.000000,867.535000
75%,18750.250000,224.900000,37.660000,5.000000,1237.910000
max,24750.010000,297.100000,49.520000,5.000000,1632.720600

In [6]:
df.isnull().sum()

delivery_id            0
delivery_partner       0
package_type           0
vehicle_type           0
delivery_mode          0
region                 0
weather_condition      0
distance_km            0
package_weight_kg      0
delivery_time_hours    0
expected_time_hours    0
delayed                0
delivery_status        0
delivery_rating        0
delivery_cost          0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.columns

Index(['delivery_id', 'delivery_partner', 'package_type', 'vehicle_type',
       'delivery_mode', 'region', 'weather_condition', 'distance_km',
       'package_weight_kg', 'delivery_time_hours', 'expected_time_hours',
       'delayed', 'delivery_status', 'delivery_rating', 'delivery_cost'],
      dtype='object')

In [9]:
df['delivery_partner'].value_counts()

delivery_partner
xpressbees          2826
fedex               2818
dhl                 2802
ekart               2801
blue dart           2798
delhivery           2786
shadowfax           2736
ecom express        2722
amazon logistics    2711
Name: count, dtype: int64

In [10]:
df['package_type'].value_counts()

package_type
fragile items       2848
pharmacy            2810
documents           2805
automobile parts    2795
electronics         2792
clothing            2767
furniture           2746
cosmetics           2744
groceries           2693
Name: count, dtype: int64

In [11]:
Categorical_cols = [col for col in df.columns if df[col].dtype == 'object']
Categorical_cols

['delivery_partner',
 'package_type',
 'vehicle_type',
 'delivery_mode',
 'region',
 'weather_condition',
 'delivery_time_hours',
 'expected_time_hours',
 'delayed',
 'delivery_status']

In [12]:
Numerical_cols = [col for col in df.columns if df[col].dtype != 'object']
Numerical_cols

['delivery_id',
 'distance_km',
 'package_weight_kg',
 'delivery_rating',
 'delivery_cost']

In [14]:
# FIX: Extract the actual hours from the corrupted datetime strings
# The original numbers were accidentally saved as nanoseconds (e.g., ...000008 = 8 hours)

df['delivery_time_hours'] = pd.to_datetime(df['delivery_time_hours']).dt.nanosecond
df['expected_time_hours'] = pd.to_datetime(df['expected_time_hours']).dt.nanosecond

In [15]:
#  FIX: Convert the delivery_id from a decimal (float) to a string text format
df['delivery_id'] = df['delivery_id'].astype(int).astype(str)

In [16]:
df[['delivery_time_hours', 'expected_time_hours','delivery_id']].head(5)

   delivery_time_hours  expected_time_hours delivery_id
0                    8                    8         250
1                    2                    3         250
2                   10                   16         250
3                    6                    8         250
4                    9                   16         250

In [19]:
df['delivery_id'].unique()

array(['250', '251', '252', ..., '24748', '24749', '24750'],
      shape=(24501,), dtype=object)

In [18]:
df

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,250,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,8,8,no,delivered,3,1632.7206
1,250,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,2,3,no,delivered,5,640.1700
2,250,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,10,16,no,delivered,4,1448.1700
3,250,dhl,electronics,ev van,same day,east,cold,269.7,12.69,6,8,no,delivered,3,1486.5700
4,250,dhl,clothing,van,two day,north,foggy,256.7,37.02,9,16,no,delivered,4,1394.5600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,24750,dhl,furniture,scooter,two day,east,foggy,80.7,3.65,4,16,no,delivered,5,414.4500
24996,24750,ecom express,automobile parts,ev van,standard,west,clear,172.9,21.42,5,24,no,delivered,5,928.7600
24997,24750,ekart,clothing,scooter,same day,east,rainy,168.4,4.85,9,8,yes,delayed,2,956.5500
24998,24750,shadowfax,documents,ev van,standard,west,stormy,37.2,8.04,6,24,no,delivered,5,210.1200
24999,24750,blue dart,pharmacy,ev bike,two day,central,rainy,279.3,5.06,7,16,no,delivered,3,1411.6800

In [20]:
df['delivery_id'].duplicated().sum()

np.int64(499)

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df['delivery_status'].value_counts()

delivery_status
delivered    18331
delayed       5341
failed        1328
Name: count, dtype: int64

In [23]:
df.to_csv('Delivery_Logistics_Cleaned.csv', index=False)
print("\nCleaned dataset saved successfully!")

Cleaned dataset saved successfully!